name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - run: npm ci
      - run: npm run build
      - run: npm run lint

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t vehicle-rental:latest .
      
      - name: Save Docker image
        run: docker save vehicle-rental:latest | gzip > vehicle-rental.tar.gz
      
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "vehicle-rental.tar.gz"
          target: "/tmp/"
      
      - name: Run deployment script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /tmp
            docker load < vehicle-rental.tar.gz
            docker stop vehicle-rental || true
            docker rm vehicle-rental || true
            docker run -d --name vehicle-rental -p 3000:3000 vehicle-rental:latest
            rm vehicle-rental.tar.gz